In [7]:
class Point:
    num1,num2=0,0
    def __init__(self,n1, n2):
        self.num1=n1
        self.num2=n2
    def __add__(self, point2):
        return Point(self.num1+point2.num1, self.num2+point2.num2)
    def show(self):
        print("({0:d}, {1:d})".format(self.num1,self.num2))
        
if __name__=="__main__":
    a=Point(1,2)
    a.show()
    b=Point(3,4)
    b.show()
    a=a+b
    a.show()
    

(1, 2)
(3, 4)
(4, 6)


In [37]:
import csv
f=open("seoul.csv","r",encoding="cp949")
data=csv.reader(f)
header=next(data)
l=[]
i=0
differ_sum=0
for row in data:
    if i==0:
        start=str(int(row[0].split('-')[1]))+"/"+str(int(row[0].split('-')[2]))
    differ_sum+=float(row[4])-float(row[3])
    i=i+1
    if i==7:
        end=str(int(row[0].split('-')[1]))+"/"+str(int(row[0].split('-')[2]))
        l.append((differ_sum,start,end))
        i=0
        differ_sum=0
l.sort(reverse=True)
print("Max Week = {0:s} ~ {1:s}".format(l[0][1], l[0][2]))
        

Max Week = 5/8 ~ 5/14


In [36]:
import matplotlib.pyplot as plt
import numpy as np
docs1=np.array([[1,1,0,1,0,1],[1,1,1,0,1,0],[1,1,0,1,0,0]])
query=np.array([1,1,0,0,1,0])

# print(docs)
# print(query)
# plt.bar([],[])# x,y
# plt.show()

[[1 1 0 1 0 1]
 [1 1 1 0 1 0]
 [1 1 0 1 0 0]]
[1 1 0 0 1 0]
